[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow_dapp = "89rLWWdw1Lb3jbCYvPFGkf3RLAUhPcmjf9pxr4KA4JyE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/purvachaudhari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
