[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow_dapp = "EciS9NNhNVVW41WKP1k4fW9nho5bRz6fXta4GEjq3hzU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/purvachaudhari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
